# Generated by Django 3.2.15 on 2023-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='My Company', max_length=100, null=True)),
                ('title', models.CharField(blank=True, default='Developer', max_length=100, null=True)),
                ('job_description', models.CharField(blank=True, max_length=500, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
